package com.moment.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import org.json.JSONException;
import org.json.JSONObject;

import java.util.Date;
// KEEP INCLUDES END


/**
 * Entity mapped to table chats.
 */

public class Chat {

    private Long id;
    private String message;
    private java.util.Date date;

    // KEEP FIELDS - put your custom fields here
    private User user;
    // KEEP FIELDS END

    public Chat() {
    }

    public Chat(Long id) {
        this.id = id;
    }

    public Chat(Long id, String message, java.util.Date date) {
        this.id = id;
        this.message = message;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here

    public Chat(String message, User user, Date date) {
        this.message = message;
        this.user = user;
        this.date = date;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void chatFromJSON(JSONObject chatObject){
        try {
            this.setId(chatObject.getLong("id"));
            this.setMessage(chatObject.getString("message"));
            long time = chatObject.getLong("time");
            time = time * 1000;
            this.setDate(new Date(time));
            User user = new User();
            user.setUserFromJson(chatObject.getJSONObject("user"));
            this.setUser(user);
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }

    // KEEP METHODS END

}
