package com.moment.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.moment.models.Moment;
import com.moment.models.User;

import com.moment.models.MomentDao;
import com.moment.models.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig momentDaoConfig;
    private final DaoConfig userDaoConfig;

    private final MomentDao momentDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        momentDaoConfig = daoConfigMap.get(MomentDao.class).clone();
        momentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        momentDao = new MomentDao(momentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Moment.class, momentDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        momentDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public MomentDao getMomentDao() {
        return momentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
